* ONE ML
  It is a platform where one can learn and visulaize various machine learning algorithms.
  This platform have code section, theory section and *playground*. Playground is the place
  where one can play with algorithm and see how it actually work.
** Algorithms
   1. Linear Regression
   2. Logistic Regression
   3. Object Detection
   4. Image Classification
      
* Setup Guide
  Make sure you are using node version <= 14

  #+BEGIN_SRC org
  1. git clone git@github.com:m1-key/OneML_ContriHub.git
  2. cd OneML_ContriHub
  3. npm install
  4. npm start
  #+END_SRC

* Contribution Guide
  Follow the below steps to contribute to this project.

  1. First setup the project. (See Setup Guide)
  2. If want to solve any existing issue, then first inform the maintainers by commenting into that issue,
     so that it can be assigned to you. 
  3. If you want to add any new feature then first create an issue for that and tag any maintainer in that,
     so that he/she can review that new feature.
  
